---
- name: Install Grafana
  hosts: main
  become: yes
  
  tasks: 
  - name: download apt key
    ansible.builtin.apt_key: 
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: add grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: update apt cache and install grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: ensure grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      state: started
      enabled: yes